### ISSUE TITLE
Detect rows in which only 1 column differs. Like weight by example

### ISSUE THREAD

**Issue by relbersumcu** [UMC-Utrecht-RWE/ConcePTION-Level1b#4]
@t-andresvaz  started with this

**Comment by relbersumcu** [comment]
@t-andresvaz  Created branch for this

**Comment by relbersumcu** [comment]
@t-andresvaz added a simple function that excludes 1 column and do a count for the remaining columns. Then it is estimating for the tails if it is numeric or character. This is working for 1 column. However, in the test data there are also example where 2 or 3 columns differ. This may need a more sophisticated method. However I implemeded the simple function in the script so the structure is already there.

**Comment by t-andresvaz** [comment]
Done!
